services:
  Sanctuaire:
    container_name: Sanctuaire
    build:
      dockerfile: Dockerfile
      context: ./Sanctuaire
    environment:
      DB_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "8000:8000"
    depends_on: BaseDeDonneeSql
    networks:
      - NetworkSanctuaire

  BaseDeDonneeSql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - NetworkSanctuaire

networks:
  NetworkSanctuaire: